config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users
  resources :users, :only => [:index, :show]
  delete "users/:id", to: "users#destroy"
  get 'interns', to: 'users#index'
  get 'grades', to: 'grades#index'
  resources :units
  resources :assignments 
  resources :submissions
  resources :announcements
  resources :comments_submissions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  has_rich_text :content
  belongs_to :user
  validates :content, presence: true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
    protect_from_forgery except: :new

  def index
    @announcements = Announcement.all
  end
  
  def new
    @announcement = Announcement.new
  end
  
  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.user_id = current_user.id
    @announcement.save
    if @announcement.save
        flash[:success] = "The announcement was successfully submitted."
        User.all.each do |user|
          AssignmentMailer.announcement_email(user).deliver
        end
        redirect_back(fallback_location: root_path)
    else 
        flash[:success] = "Announcement was not submitted correctly, please try again."
        redirect_back(fallback_location: root_path)
  
    end    
  end
  
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy
    flash[:danger] = "You have deleted that announcement."
    redirect_to announcements_path    
  end
  
    
  private
  
  def announcement_params
      params.require(:announcement).permit(:user_id, :content)
  end
    
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/index.html.erb
<h4 align = "center"> Announcements </h4>

<%@announcements.each do |announcement|%>
  <%@user = User.find(announcement.user_id)%>
  <div class="col s12 m12">
    <div class="card fill-width">
      <div class="card-content">
        <span class="card-title">
          <div class = "">
            <%if @user.profileImage.present?%>
              <%= image_tag @user.profileImage_url.to_s, class: 'material-icons circle medium profImage line-height' %>
            <%else%>
              <i class="material-icons circle medium">account_circle</i>
            <%end%>
            <%=link_to @user.fullname, user_path(@user.id)%>
          </div>
            <%=announcement.created_at.to_formatted_s(:month_and_year)%>
          </span>
      <%=announcement.content%>
      </div>
      <%if current_user.role == "teacher"%>
        <div class="card-action">
          <%=link_to "Delete Announcement", announcement_path(announcement.id), method: :delete, data: {confirm: "Are you sure you want to delete this announcement?"}, class: 'red-text'%>
        </div>
      <%end%>
    </div>

  </div>
<%end%>