config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users
  resources :users, :only => [:index, :show]
  delete "users/:id", to: "users#destroy"
  get 'interns', to: 'users#index'
  get 'grades', to: 'grades#index'
  resources :units
  resources :assignments 
  resources :submissions
  resources :announcements
  resources :comments_submissions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/submission.rb
class Submission < ApplicationRecord
    has_rich_text :content
    has_many :comments_submissions, dependent: :destroy
    belongs_to :user
    belongs_to :assignment
    validates :content, presence: true
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
    def new
        @submission = Submission.new
    end
    def create
        @submission = Submission.new(submission_params)
        @submission.user_id = current_user.id
        @submission.ontime =  !@submission.assignment.duedate.past?
        if @submission.save
            @teachers = User.where(role: "teacher")
            @link = "https://www.trinityinternship.org/assignments/" + @submission.assignment.id.to_s
            @teachers.each do |teacher|
                AssignmentMailer.submission_email(teacher, current_user, @link).deliver
            end
            flash[:success] = "The submission was successfully submitted."
            redirect_to assignment_path(@submission.assignment)
        else 
            flash[:success] = "Submission was not submitted correctly, please try again."
            redirect_back(fallback_location: root_path)
    
        end
    end
    
    def edit
    @submission = Submission.find(params[:id])
    @assignment = @submission.assignment
    require_current(@submission)
    #require_current(@comment)
    end
    
    def update
         @submission = Submission.find(params[:id])
         @assignment = @submission.assignment
        if @submission.update(update_params)
            flash.now[:success] = "The Submission has Successfully been Saved."
            redirect_to(assignment_path(@assignment))
        else
            flash.now[:success] = "That didn't work, try again later."
            redirect_to(assignment_path(@assignment))
        end        
    end
    
    def show
        @show = Submission.find(params[:id])
    end
    def destroy
        @submission = Submission.find(params[:id])
        @submission.destroy
        flash[:danger] = "You have deleted that submission."
        redirect_back(fallback_location: root_path)
                
    end    
    
    private
    
    def if_comment_owner(submission)
       if(submission.user_id == current_user.id)
            return true
        else
            return false
       end
    end
    
    def require_current(submission)
        if submission.user_id == current_user.id|| current_user.admin == true
        
        else    
            redirect_to assignment_path(@assignment)
            flash[:danger] = "You do not have the required permissions to do that."
        end
    end

    def submission_params
        params.require(:submission).permit(:user_id, :assignment_id, :content, :ontime, :points)
    end
    
    def update_params
        params.require(:submission).permit(:content, :points)
    end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def is_teacher?
    if(current_user.role == "teacher") 
      return true
    else
      return false
    end
  end
  
  def comments
    return comments_submissions
  end
end

app/views/submissions/_card.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<div class="row bullets">
    <div class="col s12 m12">
      <div class="card fill-width">
        <div class="card-content">
          <span class="card-title">
            <div class = "row">
              <%if obj.user.profileImage.present?%>
                <%= image_tag obj.user.profileImage_url.to_s, class: 'material-icons circle medium profImage line-height' %>
              <%else%>
                <i class="material-icons circle medium line-height">account_circle</i>
              <%end%>
              <b><%=link_to obj.user.fullname, user_path(obj.user.id)%></b>
              <span class = "grey-text"><small>Submitted <%=obj.created_at.to_formatted_s(:month_and_year)%></small></span>
              <!-- If Object Late -->
              <%if current_user.role == "teacher" || current_user.admin == "true" || current_user.id == obj.user_id%>
                <%if !obj.ontime%>
                  <div class="chip yellow lighten-2">
                    <p align = "center"><b>Late</b></p>
                  </div>
                <%end%>
              <%end%>
              <!-- If Object Graded -->
              <%if current_user.role == "teacher" || current_user.admin == "true" || current_user.id == obj.user_id%>
                <%if obj.assignment.totalpoints != 0%>
                  <%if obj.points != nil%>
                    <div class="chip blue lighten-2">
                      <% @grade_percentile = (Float(obj.points) /Float(obj.assignment.totalpoints)) * 100 %>
                      <p align = "center"><b><%= @grade_percentile.truncate(2) %>%</b></p>
                    </div>
                  <%end%>
                <%end%>
              <%end%>
              <a class=" same-height assignmentmore dropdown-trigger " href='#' data-target='<%=obj.id%>'><i class="material-icons">more_vert</i></a>
              <!- Dropdown content ->
              <ul id='<%=obj.id%>' class='dropdown-content'>
                <b>Comment Actions</b>
                <li class="divider" tabindex="-1"></li>
                
                  <%if current_user.id == obj.user_id%>
                    <li>
                      <%= link_to edit_submission_path(obj.id) do %>
                        <span class = "line-height"><i class="material-icons">edit</i>Edit Submission</span>
                      <%end%>
                    </li>
                  <%end%>
                
                <%if current_user.role == "teacher" || current_user.id == obj.user_id%>
                  <li>
                    <%= link_to submission_path(obj.id), method: :delete, data: {confirm: "Are you sure you want to delete this submission?"} do %>
                      <span class = "line-height"><i class="material-icons">delete</i>Delete Submission</span>
                    <% end %>
                  </li>
                <%end%>
            </div>
          </span>
          <div id = "bullets"><%=obj.content%></div>
          <div class = "row">
            <div class = "col s1">
              <span class = "grey-text">
                <%if obj.assignment%>
                  <%if current_user.role == "teacher" || current_user.admin == "true" || current_user.id == obj.user_id%>
                    <%if obj.assignment.totalpoints != 0%>
                      <%= form_for(obj, :html => {class: "form-horizontal", role: "form"}) do  |f| %>
                        <div class = "form-padding">
                          <%= f.text_field :points,  id: 'points', type: "number", class:"form-control", disabled: !is_teacher?,  placeholder: "X" %>/<%=obj.assignment.totalpoints%>
                        </div>
                      <%end%>
                    <%end%>
                  <%end%>
                <%end%>
              </span>
            </div>
          </div>           
      </div>
        <!- Comment View->
        <hr>
        <%@comments = obj.comments_submissions%>
        <%if @comments.size >0%>
          <% @comments.each do |comment| %>
          
            <div class = "comment">
             <div class = "commentIcon">
              <%if comment.user.profileImage.present?%>
                <%= image_tag comment.user.profileImage_url.to_s, class: 'material-icons circle medium profImage line-height' %>
              <%else%>
                <i class="material-icons circle medium">account_circle</i>
              <%end%>               
             </div>
             <div class = "commentText"><div id = "rcorners1"><b><%=link_to comment.user.fullname, user_path(comment.user.id)%></b>&nbsp<%=comment.commentText%>
             <a class=" commentmore dropdown-trigger" href='#' data-target='<%=comment.id%>'><i class="material-icons">more_horiz</i></a>
              </div></div>
            </div>
            <!- Dropdown content ->
            <ul id='<%=comment.id%>' class='dropdown-content'>
              <b>Comment Actions</b>
              <li class="divider" tabindex="-1"></li>
              
                <%if current_user.id == comment.user_id%>
                  <li>
                    <%= link_to edit_comments_submission_path(comment.id) do %>
                      <span class = "line-height"><i class="material-icons">edit</i>edit Comment</span>
                    <%end%>
                  </li>
                <%end%>
              
              <%if current_user.role == "teacher" || current_user.id == comment.user_id%>
                <li>
                  <%= link_to comments_submission_path(comment.id), method: :delete, data: {confirm: "Are you sure you want to delete this comment?"} do %>
                    <span class = "line-height"><i class="material-icons">delete</i>Delete Comment</span>
                  <% end %>
                </li>
              <%end%>
            </ul>
          <%end%>
        <%end%>            
        
        <!- Link to leave a comment->
        <div align = "left" class = "commentbutton" id = "<%=obj.id.to_s%>">
          <i class="material-icons icon-comment line-height">mode_comment</i><a class = "grey-text margin-side  astext">Leave a Comment</a>
        </div>
        <!- Comment Submission form->
        <div class = "hidden commentbox" id = "<%="commentbox"+obj.id.to_s%>">
          <%= form_with model: @comment do |form| %>
            <div class="field bullet">
              <%= form.text_area :commentText, class: 'commentback' %>
              <%= form.text_field :submission_id, value: obj.id, class: 'hidden' %>
            </div>
            <div class="form-group" id="submitbutton">
              <div align = "center">
                  <%= form.submit "Leave Comment",  class: "btn waves-effect waves-light" %>
              </div>
            </div>
          <% end %>            
        </div>
        <div class="card-action">
          <%=link_to "Delete Submission", submission_path(obj.id), method: :delete, data: {confirm: "Are you sure you want to delete this submission?"}, class: 'red-text'%>
        </div>
      </div>
    </div>
</div>

app/views/submissions/_form.html.erb
<%= render 'shared/errors', obj: @submission %>

<div id = "bullets">
  <%= form_with model: @submission do |form| %>
  
    <%= form.text_field :assignment_id, value: @assignment.id, class: 'hidden' %>
    <%if @assignment.assignment_type == "Mark as Finished"%>
      <%= form.text_field :content, value: "#{current_user.firstname} has marked this assignment as completed", class: 'hidden' %>
      <div class="form-group" id="submitbutton">
        <div align = "center">
            <%= form.submit "Mark as finished",  class: "btn waves-effect waves-light" %>
        </div>
      </div>  
    <%elsif @assignment.assignment_type == "Video"%>
      <%= form.text_field :content, value: "#{current_user.firstname} has watched the video.", class: 'hidden' %>
      <div class="form-group" id="submitbutton">
        <div align = "center">
            <%= form.submit "Mark video as watched",  class: "btn waves-effect waves-light margin" %>
        </div>
      </div>  
    <%else%>
      <div class="field bullet">
        <%= form.label "Submission" %>
        <%= form.rich_text_area :content %>
      </div>
      <div class="form-group" id="submitbutton">
        <div align = "center">
            <%= form.submit "Submit Assignment",  class: "btn waves-effect waves-light" %>
        </div>
      </div>
    <%end%>
  <% end %>  
</div>

app/views/submissions/edit.html.erb
<%= render 'shared/errors', obj: @submission %>

<div id = "bullets">
  <%= form_with model: @submission do |form| %>
  
    <%= form.text_field :assignment_id, value: @assignment.id, class: 'hidden' %>
    <%if @assignment.assignment_type == "Mark as Finished"%>
      <%= form.text_field :content, value: "#{current_user.firstname} has marked this assignment as completed", class: 'hidden' %>
      <div class="form-group" id="submitbutton">
        <div align = "center">
            <%= form.submit "Mark as finished",  class: "btn waves-effect waves-light" %>
        </div>
      </div>  
    <%elsif @assignment.assignment_type == "Video"%>
      <%= form.text_field :content, value: "#{current_user.firstname} has watched the video.", class: 'hidden' %>
      <div class="form-group" id="submitbutton">
        <div align = "center">
            <%= form.submit "Mark video as watched",  class: "btn waves-effect waves-light margin" %>
        </div>
      </div>  
    <%else%>
      <div class="field bullet">
        <%= form.label "Submission" %>
        <%= form.rich_text_area :content %>
      </div>
      <div class="form-group" id="submitbutton">
        <div align = "center">
            <%= form.submit "Submit Assignment",  class: "btn waves-effect waves-light" %>
        </div>
      </div>
    <%end%>
  <% end %>  
</div>

app/views/submissions/new.html.erb
<%= render 'submissions/form'%> 

app/views/submissions/show.html.erb
<p>ERROR: You cannot view a submission this way.</p>