config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users
  resources :users, :only => [:index, :show]
  delete "users/:id", to: "users#destroy"
  get 'interns', to: 'users#index'
  get 'grades', to: 'grades#index'
  resources :units
  resources :assignments 
  resources :submissions
  resources :announcements
  resources :comments_submissions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
    has_rich_text :description
    has_and_belongs_to_many :users
    has_and_belongs_to_many :assignments
    accepts_nested_attributes_for :assignments
    
    validates :name, presence: true
    #validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profileImage, ProfileImageUploader
  has_many :submissions, dependent: :destroy
  has_and_belongs_to_many :units
  has_many :assignments, :through => :units
  has_many :comments_submissions, :through => :submissions, dependent: :destroy

  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  
    def fullname
      if(firstname && lastname) 
        firstname + " " + lastname
      else
        "[Intern doesn't have a set first and last name]"
      end
    end
    def self.fullname
      if(firstname && lastname) 
        firstname + " " + lastname
      else
        "[Intern doesn't have a set first and last name]"
      end
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
    before_action :require_teacher, except: [:show, :index]

    def new
        @unit = Unit.new
    end
    
    def create
        @unit = Unit.new(unit_params)
        @unit.save
        if @unit.save
            flash[:success] = "The unit was successfully submitted."
            redirect_to units_path
        else 
            render 'new'
        end
    end
    
    def show
        @unit = Unit.find(params[:id])
        @assignments = @unit.assignments

    end
    
    def index
       @units = Unit.paginate(page: params[:page], per_page: 9)
    end
    
    def destroy
        @unit = Unit.find(params[:id])
        @unit.destroy
        flash[:danger] = "You have deleted that unit."
        redirect_to units_path
    end
    
    
    def edit
        @unit = Unit.find(params[:id])
    end
    
    def update
        @unit = Unit.find(params[:id])
        if @unit.update(unit_params)
            flash[:success] = "The unit was successfully updated."
            redirect_to unit_path(@unit)
        else
            render 'edit'
        end        
    end
    
    private
    
    def unit_params
        params.require(:unit).permit(:name, :description, user_ids: [])
    end
    
    def require_teacher
        if current_user.role == "teacher" || current_user.admin == true
        
        else    
            redirect_to units_path
            flash[:danger] = "You do not have the required permissions to do that."
        end
    end

end

app/views/units/_unit.html.erb
<%= render 'shared/errors', obj: @unit %>



<%= form_for(@unit, :html => {class: "form-horizontal", role: "form"}) do  |f| %>
    <div class="form-group">
        <div>
            <%=f.label "Unit Name"%>
            <%= f.text_field :name, class:"form-control", placeholder: "Title of Unit", autofocus: true %> 
        </div>
        <div class = "xtrapadding">
            <%=f.label "Select Intern(s)"%>
            <%= f.collection_select(:user_ids, User.where(role: "student"), :id, (:fullname) , {class: "stopDrop"}, {:multiple => true})%>
        </div>
        <div class="field">
            <b><%= f.label :description %></b>
            <%= f.rich_text_area :description %>
        </div>
        <div class="form-group" id="submitbutton">
            <div align = "center">
                <%= f.submit  class: "btn waves-effect waves-light" %>
            </div>
        </div>
    </div>
<%end%>

app/views/units/edit.html.erb
<%= render 'units/unit'%>

app/views/units/index.html.erb
<p align = "right">
  <%if current_user.role == "teacher" || current_user.admin == true%>
    <%=link_to "Create Unit", new_unit_path, class: "waves-effect waves-light btn-small blue"%>
  <%end%>
</p>

<h2 align = "center">UNITS</h2>


<div class="row2">
    <%if current_user.role == "teacher" || current_user.admin == true%>
      
    <%else%>
      <%@units = current_user.units.paginate(page: params[:page], per_page: 9)%>
    <%end%>
      <%if @units.size > 0 %>
        <% @units.each do |unit| %>
          <div class="col s12 m4 unitcol">
            <div class="card">
              <div class="card-image">
                <%= link_to image_tag("office.jpg"), unit_path(unit.id) %>
                <a class="btn-floating halfway-fab waves-effect waves-light grey dropdown-trigger" href='#' data-target='<%=unit.id%>'><i class="material-icons">settings</i></a>
              </div>
              <div class="card-content">
                  <span class="card-title black-text"><%=link_to truncate(unit.name), unit_path(unit.id)%></span>
              </div>
              <div class="card-action">
                <%=link_to "Open Unit", unit_path(unit.id)%>
                <%if current_user.role == "teacher" || current_user.admin == true%>
                  <%=link_to "Delete Unit", unit_path(unit.id), method: :delete, data: {confirm: "Are you sure you want to delete this unit?"}, class: 'red-text'%>
                <%end%>
              </div>
            </div>
          </div>
          <ul id='<%=unit.id%>' class='dropdown-content'>
            <li><%=link_to "Open Unit", unit_path(unit.id), class: "blue-text"%></li>
            <li class="divider" tabindex="-1"></li>
            <%if current_user.role == "teacher"%>
              <li>
                <%= link_to edit_unit_path(unit.id) do %>
                  <div class = "line-height"><i class="material-icons">edit</i>Edit Unit</div>
                <% end %>
              </li>
    
              <li>
                <%= link_to unit_path(unit.id), method: :delete, data: {confirm: "Are you sure you want to delete this unit?"} do %>
                  <span class = "line-height"><i class="material-icons">delete</i>Delete Unit</span>
                <% end %>
              </li>
            <%end%>
          </ul>
        <%end%>
      <%else%>
        <div class = "row">
          <div class = "top-padding" align = "center">
            <i class="large material-icons icon-light-gray">mood_bad</i>
            <h3 class = 'blue-grey-text text-lighten-4'>Uh oh!  You're not registered for any units.  Contact your teacher or supervisor and ask them to enroll you in a unit.</h3>
          </div>            
        </div>      
      <%end%>
</div>
<div align = "center">
    <%= will_paginate @units %>
</div>

app/views/units/new.html.erb
<%= render 'shared/errors', obj: @unit %>


<%= form_for(@unit, :html => {class: "form-horizontal", role: "form"}) do  |f| %>
    <div class="form-group">
        <div>
            <%=f.label "Unit Name"%>
            <%= f.text_field :name, class:"form-control", placeholder: "Title of Unit", autofocus: true %> 
        </div>
        <div class = "xtrapadding">
            <%=f.label "Select Intern(s)"%>
            <%= f.collection_select(:user_ids, User.all, :id, (:firstname + :lastname) , {placeholder: "Intern(s)"}, {multiple: true} )%>
        </div>
        <div class="field">
            <b><%= f.label :description %></b>
            <%= f.rich_text_area :description %>
        </div>
        <div class="form-group" id="submitbutton">
            <div align = "center">
                <%= f.submit  class: "btn waves-effect waves-light" %>
            </div>
        </div>
    </div>
<%end%>

app/views/units/show.html.erb
<h2 align = "center"><%=@unit.name%></h2>
<p align = "right">
  <%if current_user.role == "teacher" || current_user.admin == true%>
    <%=link_to "Create Assignment", new_assignment_path(unit_ids: @unit.id), class: "waves-effect waves-light btn-small blue"%>
  <%end%>
</p>


<%if @assignments.size > 0%>
  <ul class="collapsible white">
    <% @assignments.each do |assignment| %>
    
      <li>
        <a class=" same-height assignmentmore dropdown-trigger " href='#' data-target='<%=assignment.id%>'><i class="material-icons">more_vert</i></a>
        <%if assignment.assignment_type == "Question"%>
          <div class="collapsible-header"><i class="material-icons">assignment</i><%=assignment.name%>
</div>
        <%elsif assignment.assignment_type == "Video"%>
          <div class="collapsible-header"><i class="material-icons">videocam</i><%=assignment.name%>
</div>
        <%else%>
          <div class="collapsible-header">
              <i class="material-icons">check_circle</i><%=assignment.name%>

          </div>
        <%end%>

        <div class="collapsible-body">
          <h4><%=link_to assignment.name, assignment_path(assignment.id)%></h4>
          <p class = "lime-text text-darken-2">Due <%=assignment.duedate.to_formatted_s(:month_and_year)%></p>
          <span><%=assignment.description%></span>
          <%if current_user.role == "teacher"%>
            <hr>
            <%=link_to "Delete Assignment", assignment_path(assignment.id), method: :delete, data: {confirm: "Are you sure you want to delete this assignment?"}, class: 'red-text'%>          
          <%end%>
        </div>
      </li>
      <!- Dropdown content ->
      <ul id='<%=assignment.id%>' class='dropdown-content'>
        <b>Assignment Actions</b>
        <li class="divider" tabindex="-1"></li>
          <li>
            <%=link_to assignment_path(assignment.id) do%>
               <span class = "line-height"><i class="material-icons">open_in_browser</i>Open Assignment</span>
            <%end%>
          </li>
        <%if current_user.role == "teacher"%>
          <li>
            <%= link_to edit_assignment_path(assignment.id) do %>
              <span class = "line-height"><i class="material-icons">edit</i>Edit Assignment</span>
            <%end%>
          </li>
          <li>
            <%= link_to assignment_path(assignment.id), method: :delete, data: {confirm: "Are you sure you want to delete this assignment?"} do %>
              <span class = "line-height"><i class="material-icons">delete</i>Delete Assignment</span>
            <% end %>
          </li>
        <%end%>
      </ul>
    <%end%>
  </ul>
<%else%>
    <div class = "top-padding" align = "center">
          <i class="large material-icons icon-light-gray">wb_sunny</i>
          <h3 class = 'blue-grey-text text-lighten-4'>No Assignments!</h3>
    </div>
<%end%>